print("My Daily Routine")
print("I usually wake up at 6:30 AM.")
print("I go to school at 7:30 AM.")
print("After school, I do my homework in 1 hour.")
print("I play video games in evening.")
print("I have dinner at 8:00 PM.")
print("I spend time with family after dinner.")
print("I go to bed at 10:00 PM.")
print("Total study time in a week is 1*7 = 7 hours.")
print("This is my daily routine, and I enjoy it!")
